# Week 4: In-Class Exercise - Data Filtering & Selection

## Objective
Practice filtering techniques using the same Education Statistics dataset you cleaned last week.

## Time: ~30 minutes

## What you'll practice:
1. **Single conditions** with comparison operators
2. **Combining conditions** with & (AND), | (OR), ~ (NOT)
3. **Convenience methods**: .isin(), .between(), .str.contains()
4. **Building real questions** from data

## Dataset
Same Education Statistics from the Colombian Ministry of Education (MEN) you cleaned in Week 3.

---

## Setup
Run this cell to load libraries, load the dataset, and apply the quick clean from Week 3.

In [1]:

import pandas as pd
import numpy as np

# Load the Education Statistics dataset
df = pd.read_csv('./data/educacion_estadisticas.csv')

# Quick clean (applying what we learned in Week 3)
df['departamento'] = df['departamento'].str.upper().str.strip()
df['ano'] = df['ano'].fillna(0).astype(int)
df = df.drop_duplicates()
df = df.dropna(subset=['departamento'])

print(f"Dataset loaded and cleaned: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Years: {sorted(df['ano'].unique())}")
print(f"Departments: {df['departamento'].nunique()} unique")
df.head()

Dataset loaded and cleaned: 455 rows, 37 columns
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Departments: 41 unique

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
1,2024,86,PUTUMAYO,81100,80.03,80.01,50.77,78.12,66.49,38.12,...,6.07,3.02,90.68,10.04,4.82,8.50,3.02,7.56,12.33,4.57
2,2016,52,NARIÑO,"394,574",71.10,NaN,38.56,68.32,56.56,29.80,...,1.89,0.04,97.71,3.07,1.92,2.64,0.04,2.36,3.79,1.34
3,2024,50,META,221911,90.34,90.29,65.69,89.17,76.00,48.10,...,6.84,2.85,91.18,11.36,5.61,9.27,2.85,9.27,12.53,3.49
4,2020,5,ANTIOQUIA,1151149,93.59,93.43,70.25,88.26,83.38,47.45,...,NaN,0.79,92.19,11.46,7.12,6.48,0.79,5.92,9.37,3.17

---

## Part 1: Single Conditions (8 minutes)

Start with simple, one-condition filters using comparison operators.

### Task 1.1: Filter by exact value
Get all rows where the year (`ano`) is 2023.

**Pattern:** `df[df['column'] == value]`

Print how many rows you found.

In [2]:
# YOUR CODE HERE
# Step 1: Create the filter
# Step 2: Print the number of rows
# Step 3: Display the first few rows

df_2023 = df[df['ano']==2023]
print(f"Number of rows in filtered dataset: {len(df_2023)}")
df_2023.head()

Number of rows in filtered dataset: 33

,ano,c_digo_departamento,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta,cobertura_neta_transicion,cobertura_neta_primaria,cobertura_neta_secundaria,cobertura_neta_media,...,reprobacion,reprobacion_transicion,reprobacion_primaria,reprobacion_secundaria,reprobacion_media,repitencia,repitencia_transicion,repitencia_primaria,repitencia_secundaria,repitencia_media
0,2023,68,SANTANDER,405256,95.80,95.64,71.27,92.98,83.40,56.02,...,7.65,2.95,91.82,12.95,6.92,7.99,2.95,7.32,11.34,4.07
7,2023,73,TOLIMA,239730,99.13,99.04,76.38,98.24,83.94,54.77,...,6.47,4.21,91.72,10.13,5.28,8.61,4.21,9.19,10.89,3.31
15,2023,94,GUAINÍA,16704,71.61,71.55,62.35,70.20,36.75,10.67,...,NaN,5.96,80.41,14.54,7.97,15.69,5.96,19.12,14.73,5.24
39,2023,25,CUNDINAMARCA,sin dato,93.59,93.32,62.91,88.71,85.25,56.55,...,6.61,4.09,92.79,11.05,5.40,8.29,4.09,7.09,12.23,3.58
50,2023,99,VICHADA,33816,67.63,67.63,51.88,75.84,29.65,11.24,...,14.59,0.68,75.32,12.80,6.05,17.37,0.68,22.77,11.74,5.29

### Task 1.2: Filter with greater than
Find all rows where the total dropout rate (`desercion`) is greater than 5%.

**Question:** How many department-year combinations have a dropout rate above 5%?

In [5]:
# YOUR CODE HERE
F_desercion = df[df['desercion'] > 5]
cantidad = len(F_desercion)
print(f"Number of rows with desercion > 5: {len(F_desercion)}")
F_desercion.head()
print(cantidad)

Number of rows with desercion > 5: 92
92

### Task 1.3: Filter with less than
Find all rows where net coverage (`cobertura_neta`) is less than 70%.

**Question:** Which departments have the lowest coverage? Look at the `departamento` column in your result.

In [9]:
# YOUR CODE HERE


df[df['cobertura_neta'] < 70]['cobertura_neta'].head()
cantidad_cobertura = len(df[df['cobertura_neta'] < 70])
print(f"Number of rows with cobertura_neta < 70: {cantidad_cobertura}")

Number of rows with cobertura_neta < 70: 39

---

## Part 2: Combining Conditions (8 minutes)

Now combine multiple conditions using `&` (AND), `|` (OR), and `~` (NOT).

**Remember:** Always wrap each condition in parentheses!

### Task 2.1: AND condition
Find rows where the year is 2023 AND the dropout rate is above 5%.

**Pattern:** `df[(condition1) & (condition2)]`

**Question:** Which departments had high dropout in 2023?

In [11]:
# YOUR CODE HERE
# Show: departamento, ano, desercion columns

df_filtro = df[(df['ano']==2023) & (df['desercion'] > 5)]
print(f"Number of rows in filtered dataset: {len(df_filtro)}")
df_filtro[['departamento', 'ano', 'desercion']]

Number of rows in filtered dataset: 6

        departamento   ano  desercion
15           GUAINÍA  2023       6.03
112         AMAZONAS  2023       5.01
150          CAQUETÁ  2023       6.89
383  VALLE DEL CAUCA  2023       5.22
384        RISARALDA  2023       5.60
408         GUAVIARE  2023       5.62

### Task 2.2: OR condition
Find all rows from either Antioquia OR Valle del Cauca.

**Pattern:** `df[(condition1) | (condition2)]`

**Hint:** The department names should be uppercase (we cleaned them in setup).

In [14]:
# YOUR CODE HERE

df_filtro2 = df[(df['departamento']=='ANTIOQUIA') | (df['departamento']=='CAUCA')]
print(f"Number of rows in filtered dataset: {len(df_filtro2)}")
df_filtro2[['departamento', 'ano', 'desercion']]

Number of rows in filtered dataset: 27

    departamento   ano  desercion
4      ANTIOQUIA  2020       2.30
18         CAUCA  2018        NaN
24     ANTIOQUIA  2012       4.01
30         CAUCA  2013       3.74
32         CAUCA  2024       3.19
34     ANTIOQUIA  2011       3.97
55     ANTIOQUIA  2024       3.78
101    ANTIOQUIA  2018       3.97
108        CAUCA  2019       2.78
121    ANTIOQUIA  2023       4.83
124    ANTIOQUIA  2015       3.82
129    ANTIOQUIA  2013       3.57
151        CAUCA  2023       3.59
153        CAUCA  2016       2.84
156        CAUCA  2011       2.75
180        CAUCA  2020       1.59
201        CAUCA  2022       3.96
209        CAUCA  2015        NaN
237    ANTIOQUIA  2017       4.15
378        CAUCA  2012       4.02
385        CAUCA  2021       3.03
412        CAUCA  2017       2.76
421    ANTIOQUIA  2019       4.02
437    ANTIOQUIA  2022        NaN
465    ANTIOQUIA  2014       2.33
469    ANTIOQUIA  2021       4.81
477        CAUCA  2014       4.54

### Task 2.3: NOT condition
Get all rows EXCEPT those from the "NACIONAL" department (the national aggregate).

**Two ways to do this:**
- `df[df['departamento'] != 'NACIONAL']`
- `df[~(df['departamento'] == 'NACIONAL')]`

Try both and verify you get the same number of rows.

In [15]:
# YOUR CODE HERE
# Method 1: using !=
df_filtro3 = df[df['departamento'] != 'NACIONAL']

# Method 2: using ~
df_filtro3_alt = df[~(df['departamento'] == 'NACIONAL')]
# Compare the row counts
print(f"Number of rows in df_filtro3: {len(df_filtro3)}")
print(f"Number of rows in df_filtro3_alt: {len(df_filtro3_alt)}")

Number of rows in df_filtro3: 455
Number of rows in df_filtro3_alt: 455

---

## Part 3: Convenience Methods (7 minutes)

Use `.isin()`, `.between()`, and `.str.contains()` to write cleaner filters.

### Task 3.1: .isin() - Match a list
Find all rows from the following departments: ANTIOQUIA, BOGOTA D.C., VALLE DEL CAUCA, CUNDINAMARCA.

**Pattern:** `df[df['column'].isin([list_of_values])]`

In [36]:
# YOUR CODE HERE

df_filtro4 = df[(df['departamento'].isin(['ANTIOQUIA', 'BOGOTA D.C.', 'VALLE DEL CAUCA', 'CUNDINAMARCA'])) ]
print(f"Number of rows in filtered dataset: {len(df_filtro4)}")
df_filtro4[['departamento', 'ano', 'desercion']]

Number of rows in filtered dataset: 26

     departamento   ano  desercion
4       ANTIOQUIA  2020       2.30
11   CUNDINAMARCA  2016        NaN
24      ANTIOQUIA  2012       4.01
34      ANTIOQUIA  2011       3.97
39   CUNDINAMARCA  2023       3.77
55      ANTIOQUIA  2024       3.78
61   CUNDINAMARCA  2020       2.78
72   CUNDINAMARCA  2013       3.17
101     ANTIOQUIA  2018       3.97
121     ANTIOQUIA  2023       4.83
124     ANTIOQUIA  2015       3.82
129     ANTIOQUIA  2013       3.57
176  CUNDINAMARCA  2017       2.57
181  CUNDINAMARCA  2014       2.60
226  CUNDINAMARCA  2019       3.02
227  CUNDINAMARCA  2011       3.60
237     ANTIOQUIA  2017       4.15
266  CUNDINAMARCA  2021       4.06
281  CUNDINAMARCA  2022       3.86
325  CUNDINAMARCA  2015       3.27
399  CUNDINAMARCA  2012       2.94
421     ANTIOQUIA  2019       4.02
422  CUNDINAMARCA  2018       2.89
437     ANTIOQUIA  2022        NaN
465     ANTIOQUIA  2014       2.33
469     ANTIOQUIA  2021       4.81

### Task 3.2: .between() - Numeric range
Find all rows where the approval rate (`aprobacion`) is between 90 and 100 (inclusive).

**Pattern:** `df[df['column'].between(low, high)]`

In [35]:
# YOUR CODE HERE
df_filtro5 = df[df['aprobacion'].between(90, 100)]
print(f"Number of rows with aprobacion between 90 and 100: {len(df_filtro5)}")
df_filtro5[['departamento', 'ano', 'aprobacion']]

Number of rows with aprobacion between 90 and 100: 199

    departamento   ano  aprobacion
2         NARINO  2016       96.44
5         NARINO  2015       96.42
6         NARINO  2022       92.01
8      MAGDALENA  2011       94.98
10       CORDOBA  2011       94.29
..           ...   ...         ...
471      CAQUETA  2018       92.62
472       TOLIMA  2014       90.31
474    SANTANDER  2011       94.25
477        CAUCA  2014       95.33
478      CAQUETA  2019       92.63

[199 rows x 3 columns]

### Task 3.3: .str.contains() - Text pattern
Find all rows where the department name contains "SANTANDER".

**Pattern:** `df[df['column'].str.contains('text', na=False)]`

**Question:** Which departments match? (Hint: there should be more than one.)

In [34]:
# YOUR CODE HERE

# Print the unique department names in your result
df_filtro6 = df[df['departamento'].str.contains('SANTANDER', na=False)]
print(df_filtro6['departamento'].unique())

<StringArray>
['SANTANDER', 'NORTEDESANTANDER']
Length: 2, dtype: str

---

## Part 4: Real Questions (5 minutes)

Use everything you've learned to answer these questions about the data.

### Task 4.1: Complex filter
Find departments in 2023 where:
- Net coverage is above 80% AND
- Dropout rate is below 3%

These are the "high performing" departments. Show the department name, coverage, and dropout columns.

In [37]:
# YOUR CODE HERE
filtro = df[
    (df['ano'] == 2023) &
    (df['cobertura_neta'] > 80) &
    (df['desercion'] < 3)
]

filtro[['departamento', 'ano', 'cobertura_neta', 'desercion']].head()

    departamento   ano  cobertura_neta  desercion
51     ATLANTICO  2023           93.63       2.34
73      BOGOTADC  2023           92.40       2.82
276        CHOCO  2023           84.91       2.32
340       BOYACA  2023           91.92       2.43

### Task 4.2: Try .query()
Rewrite the filter from Task 4.1 using `.query()` instead of boolean indexing.

**Pattern:** `df.query('condition1 and condition2')`

Verify you get the same number of rows.

In [38]:
# YOUR CODE HERE
filtro_query = df.query(
    "ano == 2023 and cobertura_neta > 80 and desercion < 3"
)

len(filtro_query)

4

---

## Bonus: Design Your Own Filter (if time permits)

Think of a question you could ask about the education data. Write the filter to answer it.

Example questions:
- Which departments had improving dropout rates (2022 lower than 2020)?
- Which departments in the Llanos region (Arauca, Casanare, Meta, Vichada) have the best coverage?
- What was the range of approval rates in 2024?

In [ ]:
# YOUR QUESTION: ________________________________
# YOUR CODE HERE

---

## Summary

In this exercise you practiced:

1. **Single conditions** - `==`, `!=`, `>`, `<`, `>=`, `<=`
2. **Combining conditions** - `&` (AND), `|` (OR), `~` (NOT)
3. **Convenience methods** - `.isin()`, `.between()`, `.str.contains()`
4. **Clean syntax** - `.query()` as an alternative

Key rules:
- Use `&` `|` `~` (NOT `and` `or` `not`) for DataFrames
- Always wrap conditions in **parentheses**
- Add `na=False` to `.str.contains()`

**Next:** Complete the workshop notebook for more complex filtering scenarios and analysis.